apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: pensjonssimulator
  namespace: pensjonskalkulator
spec:
  appName: pensjonssimulator
  auth:
    name: maskinporten
    debug: true
    cache: true
    scope:
      - "nav:pensjonssimulator:simulering"
  endpoints:
    - path: /pensjonssimulator/v1/tidligst-mulig-uttak
      method: POST
      forwardHeaders:
        - Authorization
        - Content-Type
      backendHost: http://pensjonssimulator
      backendPath: /api/v1/tidligst-mulig-uttak
  openEndpoints:
    - path: /pensjonssimulator/v1/status
      method: GET
      backendHost: http://pensjonssimulator
      backendPath: /api/v1/status
