apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonssimulator
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  replicas:
    min: 3
    max: 5
    cpuThresholdPercentage: 70
  resources:
    limits:
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 1536Mi
  ingresses:
    - https://pensjonssimulator.intern.nav.no
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "spk:nav"
        - name: "klp:oftp/simulering"
      exposes:
        - name: "simulering"
          enabled: true
          product: "pensjonssimulator"
          consumers:
            - name: Gabler Pensjonstjenester
              orgno: "916833520"
            - name: KLP
              orgno: "938708606"
            - name: Oslo Pensjonsforsikring
              orgno: "982759412"
            - name: SPK
              orgno: "982583462"
            - name: Storebrand Livsforsikring
              orgno: "958995369"
            - name: Storebrand Pensjonstjenester
              orgno: "931936492"
        - name: simulering.read
          enabled: true
          product: pensjon
          separator: "/"
          delegationSource: altinn
          consumers:
            - name: Aksio
              orgno: "927613298"
            - name: Arendal kommunale pensjonskasse
              orgno: "940380014"
            - name: Drammen kommunale pensjonskasse
              orgno: "980650383"
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjonskalkulator-backend
    outbound:
      rules:
        - application: pdl-api
          namespace: pdl
          cluster: prod-fss
        - application: pensjon-pen
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjon-regler
          namespace: pensjon-regler
          cluster: prod-fss
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: prod-fss
        - application: tp
          namespace: pensjonsamhandling
          cluster: prod-fss
        - application: tjenestepensjon-simulering
      external:
        - host: maskinporten.no
        - host: pdl-api.prod-fss-pub.nais.io
        - host: pensjon-pen.prod-fss-pub.nais.io
        - host: pensjon-popp.prod-fss-pub.nais.io
        - host: pensjon-regler.prod-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
        - host: tp-api.prod-fss-pub.nais.io
        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
        - host: api.prod.spk.no
  env:
    - name: FSS_GATEWAY_SERVICE_ID
      value: prod-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
    - name: PEN_SERVICE_ID
      value: prod-fss:pensjondeployer:pensjon-pen
    - name: PEN_URL
      value: https://pensjon-pen.prod-fss-pub.nais.io
    - name: PERSONDATA_SERVICE_ID
      value: prod-fss:pdl:pdl-api
    - name: PERSONDATA_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: POPP_SERVICE_ID
      value: prod-fss:pensjonopptjening:pensjon-popp
    - name: POPP_URL
      value: https://pensjon-popp.prod-fss-pub.nais.io
    - name: REGLER_URL
      value: https://pensjon-regler.prod-fss-pub.nais.io
    - name: TJENESTEPENSJON_SERVICE_ID
      value: prod-fss:pensjonsamhandling:tp
    - name: TJENESTEPENSJON_URL
      value: https://tp-api.prod-fss-pub.nais.io
    - name: TP_SIMULERING_SERVICE_ID
      value: prod-gcp:pensjonskalkulator:tjenestepensjon-simulering
    - name: TP_SIMULERING_URL
      value: http://tjenestepensjon-simulering
    - name: SPK_STILLINGSPROSENT_PRE_2025_URL
      value: https://partner-gw.spk.no:443/nav/SimulereTjenestepensjon
    - name: SPK_TP_SIMULERING_PRE_2025_URL
      value: https://api.prod.spk.no
    - name: SPK_TP_SIMULERING_FRA_2025_URL
      value: https://api.prod.spk.no
    - name: KLP_TP_SIMULERING_FRA_2025_URL
      value: https://api.klp.no
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PS_LOGGING_LEVEL
      value: INFO
  envFrom:
    - secret: pensjonssimulator-unleash-api-token
