apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonssimulator
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses:
    - https://pensjonssimulator.intern.nav.no
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "simulering"
          enabled: true
          product: "pensjonssimulator"
          consumers:
            - orgno: "938708606" # KLP
            - orgno: "982759412" # Oslo Pensjonsforsikring
            - orgno: "982583462" # SPK
            - orgno: "931936492" # Storebrand Pensjonstjenester
        - name: simulering.read
          enabled: true
          product: pensjon
          separator: "/"
          delegationSource: altinn
          consumers:
            - orgno: "927613298" # Aksio
            - orgno: "940380014" # Arendal kommunale pensjonskasse
            - orgno: "980650383" # Drammen kommunale pensjonskasse
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjonskalkulator-backend
    outbound:
      rules:
        - application: pensjon-pen
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: prod-fss
        - application: tp
          namespace: pensjonsamhandling
          cluster: prod-fss
        - application: tjenestepensjon-simulering
      external:
        - host: maskinporten.no
        - host: pensjon-pen.prod-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
        - host: tp-api.prod-fss-pub.nais.io
  env:
    - name: FSS_GATEWAY_SERVICE_ID
      value: prod-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
    - name: PEN_SERVICE_ID
      value: prod-fss:pensjondeployer:pensjon-pen
    - name: PEN_URL
      value: https://pensjon-pen.prod-fss-pub.nais.io
    - name: TJENESTEPENSJON_SERVICE_ID
      value: prod-fss:pensjonsamhandling:tp
    - name: TJENESTEPENSJON_URL
      value: https://tp-api.prod-fss-pub.nais.io
    - name: TP_SIMULERING_SERVICE_ID
      value: prod-gcp:pensjonskalkulator:tjenestepensjon-simulering
    - name: TP_SIMULERING_URL
      value: http://tjenestepensjon-simulering
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PS_LOGGING_LEVEL
      value: INFO
