apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonssimulator
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  ingresses:
    - https://pensjonssimulator.intern.dev.nav.no
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "simulering"
          enabled: true
          product: "pensjonssimulator"
          consumers:
            - orgno: "889640782" # Nav (NB: dev only)
            - orgno: "916833520" # Gabler Pensjonstjenester
            - orgno: "938708606" # KLP
            - orgno: "982759412" # Oslo Pensjonsforsikring
            - orgno: "982583462" # SPK
            - orgno: "931936492" # Storebrand Pensjonstjenester
        - name: simulering.read
          enabled: true
          product: pensjon
          separator: "/"
          delegationSource: altinn
          consumers:
            - orgno: "889640782" # Nav (NB: dev only)
            - orgno: "927613298" # Aksio
            - orgno: "940380014" # Arendal kommunale pensjonskasse
            - orgno: "980650383" # Drammen kommunale pensjonskasse
  accessPolicy:
    inbound:
      rules:
        - application: pdl-api
          namespace: pdl
          cluster: dev-fss
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjonskalkulator-backend
        - application: azure-token-generator # dev only
          namespace: nais
        - application: tokenx-token-generator # dev only
          namespace: nais
        - application: pensjonssimulator-end-to-end-tester
    outbound:
      rules:
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjon-regler-q2
          namespace: pensjon-regler
          cluster: dev-fss
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: dev-fss
        - application: tp-q2
          namespace: pensjonsamhandling
          cluster: dev-fss
        - application: tjenestepensjon-simulering
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: pensjon-regler-q2.dev-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
        - host: tp-api-q2.dev-fss-pub.nais.io
        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
  env:
    - name: FSS_GATEWAY_SERVICE_ID
      value: dev-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: PERSONDATA_SERVICE_ID
      value: dev-fss:pdl:pdl-api
    - name: PERSONDATA_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: PEN_SERVICE_ID
      value: dev-fss:pensjon-q2:pensjon-pen-q2
    - name: PEN_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io
    - name: POPP_SERVICE_ID
      value: dev-fss:pensjonopptjening:pensjon-popp-q2
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io
    - name: REGLER_URL
      value: https://pensjon-regler-q2.dev-fss-pub.nais.io
    - name: TJENESTEPENSJON_SERVICE_ID
      value: dev-fss:pensjonsamhandling:tp-q2
    - name: TJENESTEPENSJON_URL
      value: https://tp-api-q2.dev-fss-pub.nais.io
    - name: TP_SIMULERING_SERVICE_ID
      value: dev-gcp:pensjonskalkulator:tjenestepensjon-simulering
    - name: TP_SIMULERING_URL
      value: http://tjenestepensjon-simulering
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PS_LOGGING_LEVEL
      value: DEBUG
    - name: JAVA_TOOL_OPTIONS
      value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  envFrom:
    - secret: pensjonssimulator-unleash-api-token
