apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonssimulator
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  ingresses:
    - https://pensjonssimulator.ekstern.dev.nav.no
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "simulering"
          enabled: true
          product: "pensjonssimulator"
          consumers:
            - orgno: "889640782" # NAV (NB: dev only)
            - orgno: "938708606" # KLP
            - orgno: "982583462" # SPK
            - orgno: "931936492" # Storebrand Pensjonstjenester
  accessPolicy:
    inbound:
      rules:
        - application: pensjonskalkulator-backend
        - application: azure-token-generator
          namespace: aura
        - application: tokenx-token-generator
          namespace: aura
    outbound:
      rules:
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: dev-fss
      external:
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
  env:
    - name: FSS_GATEWAY_SERVICE_ID
      value: dev-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: PEN_SERVICE_ID
      value: dev-fss:pensjon-q2:pensjon-pen-q2
    - name: PEN_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PS_LOGGING_LEVEL
      value: DEBUG
    - name: JAVA_TOOL_OPTIONS
      value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
