apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonssimulator-q1
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  ingresses:
    - https://pensjonssimulator-q1.intern.dev.nav.no
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "spk:nav"
        - name: "klp:oftp/simulering"
      exposes:
        - name: "simulering"
          enabled: true
          product: "pensjonssimulator"
          consumers:
            - name: Nav # NB: dev only
              orgno: "889640782"
            - name: Gabler Pensjonstjenester
              orgno: "916833520"
            - name: KLP
              orgno: "938708606"
            - name: Oslo Pensjonsforsikring
              orgno: "982759412"
            - name: SPK
              orgno: "982583462"
            - name: Storebrand Livsforsikring
              orgno: "958995369"
            - name: Storebrand Pensjonstjenester
              orgno: "931936492"
        - name: simulering.read
          enabled: true
          product: pensjon
          separator: "/"
          delegationSource: altinn
          consumers:
            - name: Nav # NB: dev only
              orgno: "889640782"
            - name: Aksio
              orgno: "927613298"
            - name: Arendal kommunale pensjonskasse
              orgno: "940380014"
            - name: Drammen kommunale pensjonskasse
              orgno: "980650383"
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen-q1
          namespace: pensjon-q1
          cluster: dev-fss
    outbound:
      rules:
        - application: pdl-api-q1
          namespace: pdl
          cluster: dev-fss
        - application: pensjon-pen-q1
          namespace: pensjon-q1
          cluster: dev-fss
        - application: pensjon-regler-q1
          namespace: pensjon-regler
          cluster: dev-fss
        - application: pensjon-selvbetjening-fss-gateway-q1
          namespace: pensjonselvbetjening
          cluster: dev-fss
        - application: tp-q1
          namespace: pensjonsamhandling
          cluster: dev-fss
      external:
        - host: pdl-api-q1.dev-fss-pub.nais.io
        - host: pensjon-pen-q1.dev-fss-pub.nais.io
        - host: pensjon-regler-q1.dev-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway-q1.dev-fss-pub.nais.io
        - host: tp-api-q1.dev-fss-pub.nais.io
        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
        - host: api.test.spk.no
  env:
    - name: FSS_GATEWAY_SERVICE_ID
      value: dev-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway-q1
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway-q1.dev-fss-pub.nais.io
    - name: PEN_SERVICE_ID
      value: dev-fss:pensjon-q1:pensjon-pen-q1
    - name: PEN_URL
      value: https://pensjon-pen-q1.dev-fss-pub.nais.io
    - name: PERSONDATA_SERVICE_ID
      value: dev-fss:pdl:pdl-api-q1
    - name: PERSONDATA_URL
      value: https://pdl-api-q1.dev-fss-pub.nais.io
    - name: REGLER_URL
      value: https://pensjon-regler-q1.dev-fss-pub.nais.io
    - name: TJENESTEPENSJON_SERVICE_ID
      value: dev-fss:pensjonsamhandling:tp-q1
    - name: TJENESTEPENSJON_URL
      value: https://tp-api-q1.dev-fss-pub.nais.io
    - name: SPK_STILLINGSPROSENT_PRE_2025_URL
      value: https://partner-gw.test.spk.no/nav/SimulereTjenestepensjon
    - name: SPK_TP_SIMULERING_PRE_2025_URL
      value: https://api.test.spk.no
    - name: SPK_TP_SIMULERING_FRA_2025_URL
      value: https://api.test.spk.no
    - name: KLP_TP_SIMULERING_FRA_2025_URL
      value: https://api-test.klp.no
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PS_LOGGING_LEVEL
      value: DEBUG
  envFrom:
    - secret: pensjonssimulator-unleash-api-token
