apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonssimulator-q1
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  ingresses:
    - https://pensjonssimulator-q1.intern.dev.nav.no
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "simulering"
          enabled: true
          product: "pensjonssimulator"
          consumers:
            - orgno: "889640782" # Nav (NB: dev only)
            - orgno: "938708606" # KLP
            - orgno: "982759412" # Oslo Pensjonsforsikring
            - orgno: "982583462" # SPK
            - orgno: "931936492" # Storebrand Pensjonstjenester
        - name: simulering.read
          enabled: true
          product: pensjon
          separator: "/"
          delegationSource: altinn
          consumers:
            - orgno: "889640782" # Nav (NB: dev only)
            - orgno: "927613298" # Aksio
            - orgno: "940380014" # Arendal kommunale pensjonskasse
            - orgno: "980650383" # Drammen kommunale pensjonskasse
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen-q1
          namespace: pensjon-q1
          cluster: dev-fss
    outbound:
      rules:
        - application: pensjon-pen-q1
          namespace: pensjon-q1
          cluster: dev-fss
        - application: pensjon-selvbetjening-fss-gateway-q1
          namespace: pensjonselvbetjening
          cluster: dev-fss
        - application: tp-q1
          namespace: pensjonsamhandling
          cluster: dev-fss
      external:
        - host: pensjon-pen-q1.dev-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway-q1.dev-fss-pub.nais.io
        - host: tp-api-q1.dev-fss-pub.nais.io
  env:
    - name: FSS_GATEWAY_SERVICE_ID
      value: dev-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway-q1
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway-q1.dev-fss-pub.nais.io
    - name: PEN_SERVICE_ID
      value: dev-fss:pensjon-q1:pensjon-pen-q1
    - name: PEN_URL
      value: https://pensjon-pen-q1.dev-fss-pub.nais.io
    - name: TJENESTEPENSJON_SERVICE_ID
      value: dev-fss:pensjonsamhandling:tp-q1
    - name: TJENESTEPENSJON_URL
      value: https://tp-api-q1.dev-fss-pub.nais.io
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PS_LOGGING_LEVEL
      value: DEBUG
