apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: pensjonssimulator
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: pensjonskalkulator
  secretName: pensjonssimulator-unleash-api-token
  environment: production
