= Tjenester

Simulatoren tilbyr to hovedkategorier av tjenester:

* Tjenester for eksterne samhandlere
* Tjenester for Navs egne applikasjoner

== Tjenester for samhandlere

Disse er tjenester for eksterne samhandlere (Norsk Pensjon og tjenestepensjonsordninger som KLP og SPK).

* Simuler alderspensjon V1 (kun Norsk Pensjon bruker denne)
* Simuler alderspensjon V3 (for personer født før 1963)
* Simuler alderspensjon V4 (for personer født 1963 eller senere)
* Simuler offentlig AFP etterfulgt av alderspensjon ("gammel" AFP-ordning)
* Simuler folketrygdbeholdning
* Beregn tidligst mulig uttak

=== Versjonering av samhandlertjenester

Tjenestene som er laget for samhandlere har et "avtalefestet" versjonsnummer (V1, V3 og V4). Endringer i tjenestene må avtales med samhandlerne.

NOTE: V2 ble tidligere brukt av KLP, men de gikk over til V3 sommeren 2025.

== Tjenester for Nav-applikasjoner

Dette er tjenester laget for Navs egne pensjonskalkulatorer.

* Simuler alderspensjon for angitt person
* Simuler alderspensjon anonymt (for Navs uinnloggede pensjonskalkulator)
* Simuler alderspensjon som serviceberegning (for saksbehandlere/veiledere)
* Simuler alderspensjon som grunnlag for simulering av tjenestepensjon
* Simuler folketrygdberegnet AFP i offentlig sektor ("gammel" AFP-ordning)

== Detaljer om tjenestene

Se: xref:tjenesteforskjeller.adoc[Viktige forskjeller i tjenestene]

== Litt om implementasjon

=== Simulatorkjerne

Alle tjenestene benytter den samme simulatorkjernen, men det utføres varierende logikk avhenging av simuleringstype.

Simulatorkjernen orkestrerer funksjonene som inngår i en enkeltsimulering (en simulering for et gitt sett av inndata).

Det er betydelige variasjoner i format på inn- og utdata i de forskjellige tjenestevariantene. Disse mappes til en felles inn-/utdatastruktur som brukes av kjernen.

For detaljer se: xref:Implementasjon:simulatorkjerne.adoc[Simulatorkjerne]

=== Multisimulering

Pensjonssimulatoren har noen tjenester der ett tjenestekall fører til multiple enkeltsimuleringer. Det gjelder:

* Beregn tidligst mulig uttak
* Utled alternative uttaksvilkår i tilfeller der kallets inndata gir avslag i vilkårsprøvingen

I disse tilfellene vil simulatoren generere flere sett av inndata (og simulere med hvert av dem) for å finne det settet som gir innvilgelse i vilkårsprøvingen.

For detaljer se: xref:Implementasjon:uttak.adoc[Beregning av tidligst mulig uttak]
