= Viktige forskjeller i tjenestene

== Kallende applikasjoner

Her vises hvilke applikasjoner som pensjonssimulator mottar de forskjellige tjenestekallene fra direkte ("direktekonsument"). I tillegg vises hva som er den endelige applikasjonen som tjenesten er myntet på ("sluttkonsument"), selv om dette i prinsippet er irrelevant for simulatoren.

.Kallende applikasjoner
|===
|Tjeneste |Direktekonsument |Sluttkonsument

|Simuler alderspensjon V1
|PEN
|Ekstern samhandler

|Simuler alderspensjon V3
|PEN
|Ekstern samhandler

|Simuler alderspensjon V4
|Ekstern samhandler
|Ekstern samhandler

|Simuler alderspensjon for angitt person
|pensjonskalkulator-backend
|pensjonskalkulator-frontend

|Simuler alderspensjon anonymt
|pensjonskalkulator-backend
|pensjonskalkulator-uinnlogget-frontend

|Simuler alderspensjon som serviceberegning
|PEN
|PSELV

|Simuler alderspensjon som grunnlag for simulering av tjenestepensjon
|PEN
|PSELV

|Simuler folketrygdberegnet AFP i offentlig sektor
|PEN
|PSELV

|Simuler offentlig AFP etterfulgt av alderspensjon
|Ekstern samhandler
|Ekstern samhandler

|Simuler folketrygdbeholdning
|Ekstern samhandler
|Ekstern samhandler

|Beregn tidligst mulig uttak
|Ekstern samhandler
|Ekstern samhandler

|===

== Inndata, beregning og utdata

Se: xref:tjenestesammenligning.adoc[Sammenligning av tjenester]

== Simulering av endret pensjon

Pensjonssimulator har støtte for simulering av endret pensjon (endring av løpende uttak), men ikke alle konsumentene av tjenestene benytter seg av denne støtten (og tilbyr derfor kun simulering av førstegangsuttak).

De fleste tjenestene krever at simuleringstype (førstegangsuttak/endring) angis eksplisitt. Unntakene er 'Simuler alderspensjon V4' og 'Simuler folketrygdbeholdning'. Her sjekker pensjonssimulator om personen har løpende pensjon (i så fall simuleres endring). Sjekken baserer seg på vedtaksdata som hentes fra PEN.

.Støtte for simulering av endret pensjon
|===
|Tjeneste |Støtter endring? |Simuleringstype angis av

|Simuler alderspensjon V1
|Nei^1^
|PEN

|Simuler alderspensjon V3
|Ja
|PEN

|Simuler alderspensjon V4
|Ja
|pensjonssimulator^3^

|Simuler alderspensjon for angitt person
|Ja
|pensjonskalkulator-frontend

|Simuler alderspensjon anonymt
|Nei^2^
|pensjonskalkulator-uinnlogget-frontend

|Simuler alderspensjon som serviceberegning
|Ja
|PSELV

|Simuler alderspensjon som grunnlag for simulering av tjenestepensjon
|Ja
|PSELV

|Simuler folketrygdberegnet AFP i offentlig sektor
|Ja
|PSELV

|Simuler folketrygdbeholdning
|Ja
|pensjonssimulator^3^

|Simuler offentlig AFP etterfulgt av alderspensjon
|Nei
|pensjonssimulator^4^

|Beregn tidligst mulig uttak
|Nei
|pensjonssimulator^5^

|===

^1^ Støttes i prinsippet av pensjonssimulator, men PEN angir alltid førstegangsuttak (i klassen _HentSimulertPensjonRequestConverter_ i pensjon-pen).

^2^ Støttes i prinsippet av pensjonssimulator, men pensjonskalkulator-uinnlogget-frontend angir alltid førstegangsuttak.

^3^ Implementert i klassen _OffentligSimuleringstypeDeducer_.

^4^ Implementert i klassen _AfpEtterfulgtAvAlderspensjonSpecMapperV0_.

^5^ Implementert i klassen _UttakSpecMapperV1_.

== Behandling av EPS

Tjenestene behandler EPS (ektefelle/partner/samboer) forskjellig ved endring av løpende pensjon der EPS inngår i grunnlaget:

* Simuler alderspensjon V1, V3, V4: Bruker ikke EPS når inndata angir sivilstand 'ugift'

* Øvrige tjenester: Bruker EPS selv om inndata angir sivilstand 'ugift'

(Forskjellen er implementert i _addPersongrunnlagForEpsToKravhode_ i _EndringPersongrunnlag_.)
