package no.nav.pensjon.simulator.validity

enum class ProblemType {
    UGYLDIG_UTTAKSDATO,
    UGYLDIG_UTTAKSGRAD,
    UGYLDIG_SIVILSTATUS,
    UGYLDIG_INNTEKT,
    UGYLDIG_ANTALL_AAR,
    UGYLDIG_PERSONIDENT,
    PERSON_IKKE_FUNNET,
    PERSON_FOR_LAV_ALDER,
    PERSON_FOR_HOEY_ALDER,
    UTILSTREKKELIG_INNTEKT,
    UTILSTREKKELIG_OPPTJENING,
    UTILSTREKKELIG_TRYGDETID,
    ANNEN_KLIENTFEIL,
    // Serverfeil:
    INTERN_DATA_INKONSISTENS,
    IMPLEMENTASJONSFEIL,
    TREDJEPARTSFEIL,
    ANNEN_SERVERFEIL
}
