apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: pensjonssimulator
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  appName: pensjonssimulator
  krakend: pensjonssimulator
  auth:
    name: maskinporten
    debug: false
    cache: true
    scopes:
      - nav:pensjonssimulator:simulering
      - nav:pensjon/simulering.read
      - nav:pensjon/v3/alderspensjon
  endpoints:
    - path: /pensjonssimulator/v0/simuler-afp-etterfulgt-av-alderspensjon
      method: POST
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      backendHost: http://pensjonssimulator
      backendPath: /api/v0/simuler-afp-etterfulgt-av-alderspensjon
      timeout: 40s
    - path: /simuler/alderspensjon/v3
      method: POST
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
        - tp-nr
        - hentFullAPListe
      backendHost: http://pensjonssimulator
      backendPath: /api/v3/simuler-alderspensjon
    - path: /pensjonssimulator/v4/simuler-alderspensjon
      method: POST
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      backendHost: http://pensjonssimulator
      backendPath: /api/v4/simuler-alderspensjon
      timeout: 40s
    - path: /pensjonssimulator/v1/simuler-folketrygdbeholdning
      method: POST
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      backendHost: http://pensjonssimulator
      backendPath: /api/v1/simuler-folketrygdbeholdning
      timeout: 40s
    - path: /pensjonssimulator/v0/simuler-folketrygdberegnet-afp
      method: POST
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      backendHost: http://pensjonssimulator
      backendPath: /api/v0/simuler-folketrygdberegnet-afp
      timeout: 40s
    - path: /pensjonssimulator/v1/tidligst-mulig-uttak
      method: POST
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      backendHost: http://pensjonssimulator
      backendPath: /api/v1/tidligst-mulig-uttak
      timeout: 40s
  openEndpoints:
    - path: /pensjonssimulator/v1/status
      method: GET
      backendHost: http://pensjonssimulator
      backendPath: /api/v1/status
    - path: /pensjonssimulator/api-dokumentasjon
      method: GET
      backendHost: http://pensjonssimulator
      backendPath: /v3/api-docs
