package no.nav.pensjon.simulator.common.client.pen.acl

import mu.KotlinLogging
import no.nav.pensjon.simulator.core.domain.regler.enum.LandkodeEnum
import org.springframework.util.StringUtils.hasLength
import java.util.Locale

/**
 * Corresponds with
 * no.nav.domain.pensjon.kjerne.kodetabeller.LandKode
 * in pensjon-pen
 */
enum class PenLandkode(val reglerValue: LandkodeEnum, val navn: String) {
    ABW(reglerValue = LandkodeEnum.ABW, navn = "Aruba"),
    AFG(reglerValue = LandkodeEnum.AFG, navn = "Afghanistan"),
    AGO(reglerValue = LandkodeEnum.AGO, navn = "Angola"),
    AIA(reglerValue = LandkodeEnum.AIA, navn = "Anguilla"),
    ALA(reglerValue = LandkodeEnum.ALA, navn = "Åland"),
    ALB(reglerValue = LandkodeEnum.ALB, navn = "Albania"),
    AND(reglerValue = LandkodeEnum.AND, navn = "Andorra"),
    ANT(reglerValue = LandkodeEnum.ANT, navn = "De Nederlandske Antillene"),
    ARE(reglerValue = LandkodeEnum.ARE, navn = "De Forente Arabiske Emirater"),
    ARG(reglerValue = LandkodeEnum.ARG, navn = "Argentina"),
    ARM(reglerValue = LandkodeEnum.ARM, navn = "Armenia"),
    ASM(reglerValue = LandkodeEnum.ASM, navn = "Am. Samoa"),
    ATA(reglerValue = LandkodeEnum.ATA, navn = "Antarktis"),
    ATF_V1(reglerValue = LandkodeEnum.ATF, navn = "Franske Antiller"),
    ATF(reglerValue = LandkodeEnum.ATF, navn = "De franske territoriene i sør"),
    ATG(reglerValue = LandkodeEnum.ATG, navn = "Antigua Og Barbuda"),
    AUS(reglerValue = LandkodeEnum.AUS, navn = "Australia"),
    AUT(reglerValue = LandkodeEnum.AUT, navn = "Østerrike"),
    AZE(reglerValue = LandkodeEnum.AZE, navn = "Aserbajdsjan"),
    BDI(reglerValue = LandkodeEnum.BDI, navn = "Burundi"),
    BEL(reglerValue = LandkodeEnum.BEL, navn = "Belgia"),
    BEN(reglerValue = LandkodeEnum.BEN, navn = "Benin"),
    BES(reglerValue = LandkodeEnum.BES, navn = "Bonaire, Sint Eustatius og Saba"),
    BFA(reglerValue = LandkodeEnum.BFA, navn = "Burkina Faso"),
    BGD(reglerValue = LandkodeEnum.BGD, navn = "Bangladesh"),
    BGR(reglerValue = LandkodeEnum.BGR, navn = "Bulgaria"),
    BHR(reglerValue = LandkodeEnum.BHR, navn = "Bahrain"),
    BHS(reglerValue = LandkodeEnum.BHS, navn = "Bahamas"),
    BIH(reglerValue = LandkodeEnum.BIH, navn = "Bosnia-Hercegovina"),
    BLM(reglerValue = LandkodeEnum.BLM, navn = "Saint Barthelemy"),
    BLR(reglerValue = LandkodeEnum.BLR, navn = "Belarus"),
    BLZ(reglerValue = LandkodeEnum.BLZ, navn = "Belize"),
    BMU(reglerValue = LandkodeEnum.BMU, navn = "Bermuda"),
    BOL(reglerValue = LandkodeEnum.BOL, navn = "Bolivia"),
    BRA(reglerValue = LandkodeEnum.BRA, navn = "Brasil"),
    BRB(reglerValue = LandkodeEnum.BRB, navn = "Barbados"),
    BRN(reglerValue = LandkodeEnum.BRN, navn = "Brunei"),
    BTN(reglerValue = LandkodeEnum.BTN, navn = "Bhutan"),
    BVT(reglerValue = LandkodeEnum.BVT, navn = "Bouvetøya"),
    BWA(reglerValue = LandkodeEnum.BWA, navn = "Botswana"),
    CAF(reglerValue = LandkodeEnum.CAF, navn = "Den Sentralafrikanske Republikk"),
    CAN(reglerValue = LandkodeEnum.CAN, navn = "Canada"),
    CCK(reglerValue = LandkodeEnum.CCK, navn = "Kokosøyene (Keelingøyene)"),
    CHE(reglerValue = LandkodeEnum.CHE, navn = "Sveits"),
    CHL(reglerValue = LandkodeEnum.CHL, navn = "Chile"),
    CHN(reglerValue = LandkodeEnum.CHN, navn = "Kina"),
    CIV(reglerValue = LandkodeEnum.CIV, navn = "Elfenbenskysten"),
    CMR(reglerValue = LandkodeEnum.CMR, navn = "Kamerun"),
    COD(reglerValue = LandkodeEnum.COD, navn = "Kongo"),
    COG(reglerValue = LandkodeEnum.COG, navn = "Kongo-Brazzaville"),
    COK(reglerValue = LandkodeEnum.COK, navn = "Cookøyene"),
    COL(reglerValue = LandkodeEnum.COL, navn = "Colombia"),
    COM(reglerValue = LandkodeEnum.COM, navn = "Komorene"),
    CPV(reglerValue = LandkodeEnum.CPV, navn = "Kapp Verde"),
    CRI(reglerValue = LandkodeEnum.CRI, navn = "Costa Rica"),
    CSK(reglerValue = LandkodeEnum.CSK, navn = "Tsjekkoslovakia"),
    CUB(reglerValue = LandkodeEnum.CUB, navn = "Cuba"),
    CUW(reglerValue = LandkodeEnum.CUW, navn = "Curacao"),
    CXR(reglerValue = LandkodeEnum.CXR, navn = "Christmasøya"),
    CYM(reglerValue = LandkodeEnum.CYM, navn = "Caymanøyene"),
    CYP(reglerValue = LandkodeEnum.CYP, navn = "Kypros"),
    CZE_V1(reglerValue = LandkodeEnum.CZE, navn = "Den Tsjekkiske Rep."),
    CZE(reglerValue = LandkodeEnum.CZE, navn = "Tsjekkia"),
    DDR(reglerValue = LandkodeEnum.DDR, navn = "Tyskland (Øst)"),
    DEU(reglerValue = LandkodeEnum.DEU, navn = "Tyskland"),
    DJI(reglerValue = LandkodeEnum.DJI, navn = "Djibouti"),
    DMA(reglerValue = LandkodeEnum.DMA, navn = "Dominica"),
    DNK(reglerValue = LandkodeEnum.DNK, navn = "Danmark"),
    DOM(reglerValue = LandkodeEnum.DOM, navn = "Den Dominikanske Republikk"),
    DZA(reglerValue = LandkodeEnum.DZA, navn = "Algerie"),
    ECU(reglerValue = LandkodeEnum.ECU, navn = "Ecuador"),
    EGY(reglerValue = LandkodeEnum.EGY, navn = "Egypt"),
    ERI(reglerValue = LandkodeEnum.ERI, navn = "Eritrea"),
    ESH(reglerValue = LandkodeEnum.ESH, navn = "Vest-Sahara"),
    ESP(reglerValue = LandkodeEnum.ESP, navn = "Spania"),
    EST(reglerValue = LandkodeEnum.EST, navn = "Estland"),
    ETH(reglerValue = LandkodeEnum.ETH, navn = "Etiopia"),
    FIN(reglerValue = LandkodeEnum.FIN, navn = "Finland"),
    FJI(reglerValue = LandkodeEnum.FJI, navn = "Fiji"),
    FLK(reglerValue = LandkodeEnum.FLK, navn = "Falklandsøyene"),
    FRA(reglerValue = LandkodeEnum.FRA, navn = "Frankrike"),
    FRO(reglerValue = LandkodeEnum.FRO, navn = "Færøyene"),
    FSM(reglerValue = LandkodeEnum.FSM, navn = "Mikronesiaføderasjonen"),
    GAB(reglerValue = LandkodeEnum.GAB, navn = "Gabon"),
    GBR(reglerValue = LandkodeEnum.GBR, navn = "Storbritannia"),
    GEO(reglerValue = LandkodeEnum.GEO, navn = "Georgia"),
    GGY(reglerValue = LandkodeEnum.GGY, navn = "Guernsey"),
    GHA(reglerValue = LandkodeEnum.GHA, navn = "Ghana"),
    GIB(reglerValue = LandkodeEnum.GIB, navn = "Gibraltar"),
    GIN(reglerValue = LandkodeEnum.GIN, navn = "Guinea"),
    GLP(reglerValue = LandkodeEnum.GLP, navn = "Guadeloupe"),
    GMB(reglerValue = LandkodeEnum.GMB, navn = "Gambia"),
    GNB(reglerValue = LandkodeEnum.GNB, navn = "Guinea-Bissau"),
    GNQ(reglerValue = LandkodeEnum.GNQ, navn = "Ekvatorial-Guinea"),
    GRC(reglerValue = LandkodeEnum.GRC, navn = "Hellas"),
    GRD(reglerValue = LandkodeEnum.GRD, navn = "Grenada"),
    GRL(reglerValue = LandkodeEnum.GRL, navn = "Grønland"),
    GTM(reglerValue = LandkodeEnum.GTM, navn = "Guatemala"),
    GUF(reglerValue = LandkodeEnum.GUF, navn = "Fransk Guyana"),
    GUM(reglerValue = LandkodeEnum.GUM, navn = "Guam"),
    GUY(reglerValue = LandkodeEnum.GUY, navn = "Guyana"),
    HKG(reglerValue = LandkodeEnum.HKG, navn = "Hongkong"),
    HMD(reglerValue = LandkodeEnum.HMD, navn = "Heard- og McDonaldøyene"),
    HND(reglerValue = LandkodeEnum.HND, navn = "Honduras"),
    HRV(reglerValue = LandkodeEnum.HRV, navn = "Kroatia"),
    HTI(reglerValue = LandkodeEnum.HTI, navn = "Haiti"),
    HUN(reglerValue = LandkodeEnum.HUN, navn = "Ungarn"),
    IDN(reglerValue = LandkodeEnum.IDN, navn = "Indonesia"),
    IMN(reglerValue = LandkodeEnum.IMN, navn = "Isle of Man"),
    IND(reglerValue = LandkodeEnum.IND, navn = "India"),
    IOT(reglerValue = LandkodeEnum.IOT, navn = "Det britiske territoriet i Indiahavet"),
    IRL(reglerValue = LandkodeEnum.IRL, navn = "Irland"),
    IRN(reglerValue = LandkodeEnum.IRN, navn = "Iran"),
    IRQ(reglerValue = LandkodeEnum.IRQ, navn = "Irak"),
    ISL(reglerValue = LandkodeEnum.ISL, navn = "Island"),
    ISR(reglerValue = LandkodeEnum.ISR, navn = "Israel"),
    ITA(reglerValue = LandkodeEnum.ITA, navn = "Italia"),
    JAM(reglerValue = LandkodeEnum.JAM, navn = "Jamaica"),
    JEY(reglerValue = LandkodeEnum.JEY, navn = "Jersey"),
    JOR(reglerValue = LandkodeEnum.JOR, navn = "Jordan"),
    JPN(reglerValue = LandkodeEnum.JPN, navn = "Japan"),
    KAZ(reglerValue = LandkodeEnum.KAZ, navn = "Kasakhstan"),
    KEN(reglerValue = LandkodeEnum.KEN, navn = "Kenya"),
    KGZ(reglerValue = LandkodeEnum.KGZ, navn = "Kirgisistan"),
    KHM(reglerValue = LandkodeEnum.KHM, navn = "Kambodsja"),
    KIR(reglerValue = LandkodeEnum.KIR, navn = "Kiribati"),
    KNA(reglerValue = LandkodeEnum.KNA, navn = "Saint Kitts og Nevis"),
    KOR(reglerValue = LandkodeEnum.KOR, navn = "Sør-Korea"),
    KWT(reglerValue = LandkodeEnum.KWT, navn = "Kuwait"),
    LAO(reglerValue = LandkodeEnum.LAO, navn = "Laos"),
    LBN(reglerValue = LandkodeEnum.LBN, navn = "Libanon"),
    LBR(reglerValue = LandkodeEnum.LBR, navn = "Liberia"),
    LBY(reglerValue = LandkodeEnum.LBY, navn = "Libya"),
    LCA(reglerValue = LandkodeEnum.LCA, navn = "Saint Lucia"),
    LIE(reglerValue = LandkodeEnum.LIE, navn = "Liechtenstein"),
    LKA(reglerValue = LandkodeEnum.LKA, navn = "Sri Lanka"),
    LSO(reglerValue = LandkodeEnum.LSO, navn = "Lesotho"),
    LTU(reglerValue = LandkodeEnum.LTU, navn = "Litauen"),
    LUX(reglerValue = LandkodeEnum.LUX, navn = "Luxembourg"),
    LVA(reglerValue = LandkodeEnum.LVA, navn = "Latvia"),
    MAC(reglerValue = LandkodeEnum.MAC, navn = "Macao"),
    MAF(reglerValue = LandkodeEnum.MAF, navn = "Saint Martin"),
    MAR(reglerValue = LandkodeEnum.MAR, navn = "Marokko"),
    MCO(reglerValue = LandkodeEnum.MCO, navn = "Monaco"),
    MDA(reglerValue = LandkodeEnum.MDA, navn = "Moldova"),
    MDG(reglerValue = LandkodeEnum.MDG, navn = "Madagaskar"),
    MDV(reglerValue = LandkodeEnum.MDV, navn = "Maldivene"),
    MEX(reglerValue = LandkodeEnum.MEX, navn = "Mexico"),
    MHL(reglerValue = LandkodeEnum.MHL, navn = "Marshalløyene"),
    MKD(reglerValue = LandkodeEnum.MKD, navn = "Nord-Makedonia"),
    MLI(reglerValue = LandkodeEnum.MLI, navn = "Mali"),
    MLT(reglerValue = LandkodeEnum.MLT, navn = "Malta"),
    MMR(reglerValue = LandkodeEnum.MMR, navn = "Myanmar (Burma)"),
    MNE(reglerValue = LandkodeEnum.MNE, navn = "Montenegro"),
    MNG(reglerValue = LandkodeEnum.MNG, navn = "Mongolia"),
    MNP(reglerValue = LandkodeEnum.MNP, navn = "Nord-Marianene"),
    MOZ(reglerValue = LandkodeEnum.MOZ, navn = "Mosambik"),
    MRT(reglerValue = LandkodeEnum.MRT, navn = "Mauritania"),
    MSR(reglerValue = LandkodeEnum.MSR, navn = "Montserrat"),
    MTQ(reglerValue = LandkodeEnum.MTQ, navn = "Martinique"),
    MUS(reglerValue = LandkodeEnum.MUS, navn = "Mauritius"),
    MWI(reglerValue = LandkodeEnum.MWI, navn = "Malawi"),
    MYS(reglerValue = LandkodeEnum.MYS, navn = "Malaysia"),
    MYT(reglerValue = LandkodeEnum.MYT, navn = "Mayotte"),
    NAM(reglerValue = LandkodeEnum.NAM, navn = "Namibia"),
    NCL(reglerValue = LandkodeEnum.NCL, navn = "Ny-Caledonia"),
    NER(reglerValue = LandkodeEnum.NER, navn = "Niger"),
    NFK(reglerValue = LandkodeEnum.NFK, navn = "Norfolkøya"),
    NGA(reglerValue = LandkodeEnum.NGA, navn = "Nigeria"),
    NIC(reglerValue = LandkodeEnum.NIC, navn = "Nicaragua"),
    NIU(reglerValue = LandkodeEnum.NIU, navn = "Niue"),
    NLD(reglerValue = LandkodeEnum.NLD, navn = "Nederland"),
    NOR(reglerValue = LandkodeEnum.NOR, navn = "Norge"),
    NPL(reglerValue = LandkodeEnum.NPL, navn = "Nepal"),
    NRU(reglerValue = LandkodeEnum.NRU, navn = "Nauru"),
    NZL(reglerValue = LandkodeEnum.NZL, navn = "New Zealand"),
    OMN(reglerValue = LandkodeEnum.OMN, navn = "Oman"),
    PAK(reglerValue = LandkodeEnum.PAK, navn = "Pakistan"),
    PAN(reglerValue = LandkodeEnum.PAN, navn = "Panama"),
    PCN(reglerValue = LandkodeEnum.PCN, navn = "Pitcairn"),
    PER(reglerValue = LandkodeEnum.PER, navn = "Peru"),
    PHL(reglerValue = LandkodeEnum.PHL, navn = "Filippinene"),
    PLW(reglerValue = LandkodeEnum.PLW, navn = "Palau"),
    PNG(reglerValue = LandkodeEnum.PNG, navn = "Papua Ny-Guinea"),
    POL(reglerValue = LandkodeEnum.POL, navn = "Polen"),
    PRI(reglerValue = LandkodeEnum.PRI, navn = "Puerto Rico"),
    PRK(reglerValue = LandkodeEnum.PRK, navn = "Nord-Korea"),
    PRT(reglerValue = LandkodeEnum.PRT, navn = "Portugal"),
    PRY(reglerValue = LandkodeEnum.PRY, navn = "Paraguay"),
    PSE(reglerValue = LandkodeEnum.PSE, navn = "Palestina"),
    PYF(reglerValue = LandkodeEnum.PYF, navn = "Fransk Polynesia"),
    P_349(reglerValue = LandkodeEnum.P_349, navn = "Spanske Omr. Afrika"),
    P_546(reglerValue = LandkodeEnum.P_546, navn = "Sikkim"),
    P_556(reglerValue = LandkodeEnum.P_556, navn = "Yemen"),
    P_669(reglerValue = LandkodeEnum.P_669, navn = "Panamakanalsonen"),
    P_UnkUnkUnk(reglerValue = LandkodeEnum.P_UnkUnkUnk, navn = "Uoppgitt/Ukjent"),
    QAT(reglerValue = LandkodeEnum.QAT, navn = "Qatar"),
    QEB(reglerValue = LandkodeEnum.QEB, navn = "Quebec"),
    REU_V1(reglerValue = LandkodeEnum.REU, navn = "Le Port"),
    REU(reglerValue = LandkodeEnum.REU, navn = "Reunion"),
    ROU(reglerValue = LandkodeEnum.ROU, navn = "Romania"),
    RUS(reglerValue = LandkodeEnum.RUS, navn = "Russland"),
    RWA(reglerValue = LandkodeEnum.RWA, navn = "Rwanda"),
    SAU(reglerValue = LandkodeEnum.SAU, navn = "Saudi-Arabia"),
    SCG(reglerValue = LandkodeEnum.SCG, navn = "Serbia Og Montenegro"),
    SDN(reglerValue = LandkodeEnum.SDN, navn = "Sudan"),
    SEN(reglerValue = LandkodeEnum.SEN, navn = "Senegal"),
    SGP(reglerValue = LandkodeEnum.SGP, navn = "Singapore"),
    SGS(reglerValue = LandkodeEnum.SGS, navn = "Sør-Georgia og Sør-Sandwichøyene"),
    SHN(reglerValue = LandkodeEnum.SHN, navn = "Sankt Helena, Ascension og Tristan da Cunha"),
    SJM_V1(reglerValue = LandkodeEnum.SJM, navn = "Svalbard Og Jan Mayen"),
    SJM(reglerValue = LandkodeEnum.SJM, navn = "Svalbard og Jan Mayen"),
    SLB(reglerValue = LandkodeEnum.SLB, navn = "Salomonøyene"),
    SLE(reglerValue = LandkodeEnum.SLE, navn = "Sierra Leone"),
    SLV(reglerValue = LandkodeEnum.SLV, navn = "El Salvador"),
    SMR(reglerValue = LandkodeEnum.SMR, navn = "San Marino"),
    SOM(reglerValue = LandkodeEnum.SOM, navn = "Somalia"),
    SPM(reglerValue = LandkodeEnum.SPM, navn = "Saint-Pierre og Miquelon"),
    SRB(reglerValue = LandkodeEnum.SRB, navn = "Serbia"),
    SSD(reglerValue = LandkodeEnum.SSD, navn = "Sør-Sudan"),
    STP(reglerValue = LandkodeEnum.STP, navn = "Sao Tome Og Principe"),
    SUN(reglerValue = LandkodeEnum.SUN, navn = "Sovjetunionen"),
    SUR(reglerValue = LandkodeEnum.SUR, navn = "Suriname"),
    SVK(reglerValue = LandkodeEnum.SVK, navn = "Slovakia"),
    SVN(reglerValue = LandkodeEnum.SVN, navn = "Slovenia"),
    SWE(reglerValue = LandkodeEnum.SWE, navn = "Sverige"),
    SWZ(reglerValue = LandkodeEnum.SWZ, navn = "Eswatini"),
    SXM(reglerValue = LandkodeEnum.SXM, navn = "Sint Maarten"),
    SYC(reglerValue = LandkodeEnum.SYC, navn = "Seychellene"),
    SYR(reglerValue = LandkodeEnum.SYR, navn = "Syria"),
    TCA(reglerValue = LandkodeEnum.TCA, navn = "Turks- og Caicosøyene"),
    TCD(reglerValue = LandkodeEnum.TCD, navn = "Tchad"),
    TGO(reglerValue = LandkodeEnum.TGO, navn = "Togo"),
    THA(reglerValue = LandkodeEnum.THA, navn = "Thailand"),
    TJK(reglerValue = LandkodeEnum.TJK, navn = "Tadsjikistan"),
    TKL(reglerValue = LandkodeEnum.TKL, navn = "Tokelau"),
    TKM(reglerValue = LandkodeEnum.TKM, navn = "Turkmenistan"),
    TLS(reglerValue = LandkodeEnum.TLS, navn = "Øst-Timor"),
    TON(reglerValue = LandkodeEnum.TON, navn = "Tonga"),
    TTO(reglerValue = LandkodeEnum.TTO, navn = "Trinidad Og Tobago"),
    TUN(reglerValue = LandkodeEnum.TUN, navn = "Tunisia"),
    TUR(reglerValue = LandkodeEnum.TUR, navn = "Tyrkia"),
    TUV(reglerValue = LandkodeEnum.TUV, navn = "Tuvalu"),
    TWN(reglerValue = LandkodeEnum.TWN, navn = "Taiwan"),
    TZA(reglerValue = LandkodeEnum.TZA, navn = "Tanzania"),
    UGA(reglerValue = LandkodeEnum.UGA, navn = "Uganda"),
    UKR(reglerValue = LandkodeEnum.UKR, navn = "Ukraina"),
    UMI(reglerValue = LandkodeEnum.UMI, navn = "Usas ytre småøyer"),
    URY(reglerValue = LandkodeEnum.URY, navn = "Uruguay"),
    USA(reglerValue = LandkodeEnum.USA, navn = "USA"),
    UZB(reglerValue = LandkodeEnum.UZB, navn = "Usbekistan"),
    VAT(reglerValue = LandkodeEnum.VAT, navn = "Vatikanstaten"),
    VCT(reglerValue = LandkodeEnum.VCT, navn = "Saint Vincent og Grenadinene"),
    VEN(reglerValue = LandkodeEnum.VEN, navn = "Venezuela"),
    VGB(reglerValue = LandkodeEnum.VGB, navn = "De britiske Jomfruøyer"),
    VIR(reglerValue = LandkodeEnum.VIR, navn = "De amerikanske Jomfruøyer"),
    VNM(reglerValue = LandkodeEnum.VNM, navn = "Vietnam"),
    VUT(reglerValue = LandkodeEnum.VUT, navn = "Vanuatu"),
    WAK(reglerValue = LandkodeEnum.WAK, navn = "Wakøya"),
    WLF(reglerValue = LandkodeEnum.WLF, navn = "Wallis og Futuna"),
    WSM(reglerValue = LandkodeEnum.WSM, navn = "Samoa"),
    XUK(reglerValue = LandkodeEnum.XUK, navn = "Uoppgitt/Ukjent"),
    XXK(reglerValue = LandkodeEnum.XXK, navn = "Kosovo"),
    XXX(reglerValue = LandkodeEnum.XXX, navn = "Statløs"),
    YEM(reglerValue = LandkodeEnum.YEM, navn = "Yemen"),
    YUG(reglerValue = LandkodeEnum.YUG, navn = "Jugoslavia"),
    ZAF(reglerValue = LandkodeEnum.ZAF, navn = "Sør-Afrika"),
    ZMB(reglerValue = LandkodeEnum.ZMB, navn = "Zambia"),
    ZWE(reglerValue = LandkodeEnum.ZWE, navn = "Zimbabwe"),
    // Special values not in pensjon-pen (used for missing/unknown values):
    NONE(reglerValue = LandkodeEnum.XUK, navn = "(uoppgitt)"),
    UNKNOWN(reglerValue = LandkodeEnum.XUK, navn = "(ukjent)");

    companion object {
        private val log = KotlinLogging.logger {}

        private val landkoderByExternalValue: Map<String, PenLandkode> =
            entries.associateBy { it.name.lowercase(Locale.ROOT) }

        fun internalValue(externalValue: String?): LandkodeEnum =
            fromExternalValue(externalValue).reglerValue

        private fun fromExternalValue(value: String?) =
            value?.let { landkoderByExternalValue[it.lowercase(Locale.ROOT)] }
                ?: default(externalValue = value)

        private fun default(externalValue: String?) =
            if (hasLength(externalValue))
                UNKNOWN.also { log.warn { "Unknown PEN landkode '$externalValue'" } }
            else
                NONE
    }
}