= Simulatorkjerne

Simulatorkjernen er komponenten som utfører de overordnede stegene for en enkeltsimulering.

Inndata er hovedsakelig:

* Simuleringstype
* Personopplysninger (fødselsnummer, sivilstand, inntekt, utenlandsopphold, m.m.)
* Ønsket uttaksalder og uttaksgrad
* Om personen kommer til å ha rett til offentlig/privat AFP

Utdata er:

* Beregnet alderspensjon fra folketrygden
* Eventuell beregnet offentlig/privat AFP
* Pensjonsbeholdning

Kotlin-implementasjonen av simulatorkjernen heter _SimulatorCore_.

For en forklaring på noen av begrepene som brukes i implementasjonen, se xref:Terminologi:pensjonsbegreper.adoc[pensjonsbegreper] og xref:Terminologi:personbegreper.adoc[personbegreper].

== Overordnet flyt

Simulering innbefatter følgende overordnede steg:

. xref:opprett-kravhode.adoc[Opprettelse av kravhode]
. xref:privat-afp.adoc[Beregning av AFP i privat sektor]
. xref:oppdater-kravhode.adoc[Oppdatering av kravhodet]
. xref:knekkpunkter.adoc[Utledning av knekkpunkter]
. xref:offentlig-afp.adoc[Beregning av AFP i offentlig sektor]
. xref:vilkårsprøv-beregn.adoc[Vilkårsprøving og beregning av alderspensjon]
