CREATE TABLE IF NOT EXISTS SIMULERING_TELLER
(
    ORG_NR          CHAR(9)     NOT NULL,
    SIMULERINGSTYPE VARCHAR(50) NOT NULL,
    ANTALL          BIGINT      NOT NULL,
    CONSTRAINT SIMULERING_TELLER_PK PRIMARY KEY (ORG_NR, SIMULERINGSTYPE)
);

-- Gabler Pensjonstjenester:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('916833520', 'ALDER', 0);
-- KLP:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('938708606', 'ALDER', 0);
-- Oslo Pensjonsforsikring:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('982759412', 'ALDER', 0);
-- SPK:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('982583462', 'ALDER', 0);
-- Storebrand Livsforsikring:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('958995369', 'ALDER', 0);
-- Storebrand Pensjonstjenester:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('931936492', 'ALDER', 0);
-- Aksio:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('927613298', 'ALDER', 0);
-- Arendal kommunale pensjonskasse:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('940380014', 'ALDER', 0);
-- Drammen kommunale pensjonskasse:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('980650383', 'ALDER', 0);
-- Pensjonsordningen for apotekvirksomhet:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('940291380', 'ALDER', 0);
-- Viken:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('974358603', 'ALDER', 0);
-- Norsk Pensjon:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('890050212', 'ALDER', 0);
-- Nav:
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'AFP', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'AFP_ETTERF_ALDER', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'AFP_FPP', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ALDER', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ALDER_KAP_20', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ALDER_M_AFP_PRIVAT', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ALDER_MED_AFP_OFFENTLIG_LIVSVARIG', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ALDER_M_GJEN', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'BARN', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ENDR_ALDER', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ENDR_ALDER_M_GJEN', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ENDR_AP_M_AFP_PRIVAT', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'ENDR_AP_M_AFP_OFFENTLIG_LIVSVARIG', 0);
INSERT INTO SIMULERING_TELLER(ORG_NR, SIMULERINGSTYPE, ANTALL) VALUES ('889640782', 'GJENLEVENDE', 0);