CREATE TABLE IF NOT EXISTS PENSJONSSIMULATOR.SIMULERING_TELLER_SNAPSHOT
(
    AAR_MAANED INT       NOT NULL,
    TIDSPUNKT  TIMESTAMP NOT NULL,
    STATISTIKK TEXT      NOT NULL,
    CONSTRAINT SIMULERING_TELLER_SNAPSHOT_PK PRIMARY KEY (AAR_MAANED)
);