package no.nav.pensjon.simulator.core.domain.regler.enum

import no.nav.pensjon.simulator.alderspensjon.PensjonType

/**
 * pensjon-regler-api: no/nav/pensjon/regler/domain/enum/YtelseskomponentTypeEnum.kt
 */
enum class YtelseskomponentTypeEnum(val pensjonType: PensjonType) {
    // SIMDOM-ADD: PensjonType
    GP(pensjonType = PensjonType.NONE),
    PT(pensjonType = PensjonType.NONE),
    TP(pensjonType = PensjonType.NONE),
    ST(pensjonType = PensjonType.NONE),
    ET(pensjonType = PensjonType.NONE),
    IP(pensjonType = PensjonType.INNTEKTSPENSJON),
    TFB(pensjonType = PensjonType.NONE),
    TSB(pensjonType = PensjonType.NONE),
    AFP_T(pensjonType = PensjonType.NONE),
    FAM_T(pensjonType = PensjonType.NONE),
    FAST_UTGIFT_T(pensjonType = PensjonType.NONE),
    `8_5_1_T`(pensjonType = PensjonType.NONE),
    VT(pensjonType = PensjonType.NONE),
    KRIG_GY(pensjonType = PensjonType.NONE),
    HJELP_I_HUS(pensjonType = PensjonType.NONE),
    HJELP_BIDRAG(pensjonType = PensjonType.NONE),
    GT_EOS(pensjonType = PensjonType.NONE),
    GT_NORDISK(pensjonType = PensjonType.NONE),
    MENDEL(pensjonType = PensjonType.NONE),
    DIFF_BER(pensjonType = PensjonType.NONE),
    SEG(pensjonType = PensjonType.NONE),
    AFP_LIVSVARIG(pensjonType = PensjonType.NONE),
    AFP_PRIVAT_LIVSVARIG(pensjonType = PensjonType.NONE),
    AFP_OFFENTLIG_LIVSVARIG(pensjonType = PensjonType.NONE),
    AFP_KRONETILLEGG(pensjonType = PensjonType.NONE),
    AFP_KOMP_TILLEGG(pensjonType = PensjonType.NONE),
    SKJERMT(pensjonType = PensjonType.NONE),
    FREM_AFP_LIVSVARIG(pensjonType = PensjonType.NONE),
    UT_ORDINER(pensjonType = PensjonType.NONE),
    UT_TFB(pensjonType = PensjonType.NONE),
    UT_TSB(pensjonType = PensjonType.NONE),
    UT_ET(pensjonType = PensjonType.NONE),
    UT_GJT(pensjonType = PensjonType.NONE),
    AAP(pensjonType = PensjonType.NONE),
    UT_AAP(pensjonType = PensjonType.NONE),
    UT_FAST_UTGIFT_T(pensjonType = PensjonType.NONE),
    UT_GT_NORDISK(pensjonType = PensjonType.NONE),
    GJENLEVTILLEGG_AP(pensjonType = PensjonType.NONE),
    SKATT_F_GP(pensjonType = PensjonType.NONE),
    SKATT_F_UT_ORDINER(pensjonType = PensjonType.NONE),
    SP(pensjonType = PensjonType.NONE),
    UT_SP(pensjonType = PensjonType.NONE),
    UFORETILLEGG_AP(pensjonType = PensjonType.NONE),
    GAP(pensjonType = PensjonType.GARANTIPENSJON),
    GAT(pensjonType = PensjonType.NONE),
    MIN_NIVA_TILL_INDV(pensjonType = PensjonType.NONE),
    MIN_NIVA_TILL_PPAR(pensjonType = PensjonType.NONE),
    TEMP(pensjonType = PensjonType.NONE),
    AP_GJT(pensjonType = PensjonType.NONE),
    AP_GJT_KAP19(pensjonType = PensjonType.NONE)
}
